//@reference(MooTools.Core.js)
//@reference(MooTools.Array.js)
//@reference(MooTools.String.js)
//@reference(MooTools.Function.js)
//@reference(MooTools.Number.js)
//@reference(MooTools.Hash.js)
//@include(Calyptus.ClientSide.Lib.MooTools.More.Utilities.Color.js)
