//@reference(MooTools.Browser.js)
//@reference(MooTools.Array.js)
//@reference(MooTools.Function.js)
//@reference(MooTools.Number.js)
//@reference(MooTools.String.js)
//@reference(MooTools.Hash.js)
//@include(Calyptus.ClientSide.Lib.MooTools.Core.Native.Event.js)
