//@reference(MooTools.Core.Browser.js)
//@reference(MooTools.Native.Array.js)
//@reference(MooTools.Native.Function.js)
//@reference(MooTools.Native.Number.js)
//@reference(MooTools.Native.String.js)
//@reference(MooTools.Native.Hash.js)
//@include(Calyptus.ClientSide.JavaScript.MooTools.Native.Event.js)
