//@reference(MooTools.Class.Extras.js)
//@reference(MooTools.Element.Event.js)
//@reference(MooTools.Element.Style.js)
//@reference(MooTools.Element.Dimensions.js)
//@include(Calyptus.ClientSide.Lib.MooTools.More.Interface.Tips.js)
