//@reference(../Core/Core.js)
//@reference(../Native/Array.js)
//@reference(../Native/String.js)
//@reference(../Native/Function.js)
//@reference(../Native/Number.js)
//@reference(../Native/Hash.js)
//@include(../../Source/Plugins/Color.js)
