//@reference(MooTools.Class.Class.Extras.js)
//@reference(MooTools.Element.Element.Event.js)
//@reference(MooTools.Element.Element.Style.js)
//@reference(MooTools.Element.Element.Dimensions.js)
//@include(Calyptus.ClientSide.JavaScript.MooTools.Plugins.Tips.js)
